import Providers from "@/app/encounters/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          {/* Include shared UI here e.g. a header or sidebar */}

          <Providers>
            <div className="md:m-5">{children}</div>
          </Providers>
        </section>
      </body>
    </html>
  );
}
