import {
  EyeOff,
  Heart,
  VolumeX,
  AlertTriangle,
  Hand,
  Eye,
  Anchor,
  ArrowDownCircle,
  Lock,
  ZapOff,
  Moon,
  ThermometerSun,
  Skull,
  ToyBrick,
  XCircle,
  GripHorizontal,
  HeartPulse,
  MessageCircle,
  Sliders,
  Timer,
  Thermometer,
} from "lucide-react";
import React from "react";

const dndEffects = [
  "Blinded",
  "Charmed",
  "Deafened",
  "Frightened",
  "Grappled",
  "Incapacitated",
  "Invisible",
  "Paralyzed",
  "Petrified",
  "Poisoned",
  "Prone",
  "Restrained",
  "Stunned",
  "Unconscious",
  "Exhaustion",
] as const;

export const effectColorMap: Record<(typeof dndEffects)[number], string> = {
  Blinded: "gray",
  Charmed: "pink",
  Deafened: "blue",
  Frightened: "yellow",
  Grappled: "green",
  Incapacitated: "red",
  Invisible: "purple",
  Paralyzed: "indigo",
  Petrified: "stone",
  Poisoned: "lime",
  Prone: "orange",
  Restrained: "teal",
  Stunned: "violet",
  Unconscious: "slate",
  Exhaustion: "amber",
};

export const effectIconMap = {
  Blinded: <EyeOff />,
  Charmed: <Heart />,
  Deafened: <VolumeX />,
  Frightened: <AlertTriangle />,
  Grappled: <Hand />,
  Incapacitated: <XCircle />,
  Invisible: <Eye />,
  Paralyzed: <Anchor />,
  Petrified: <ToyBrick />,
  Poisoned: <Skull />,
  Prone: <ArrowDownCircle />,
  Restrained: <Lock />,
  Stunned: <ZapOff />,
  Unconscious: <Moon />,
  Exhaustion: <ThermometerSun />,
};

export const mcdm_effectIconMap = {
  BLOODIED: <HeartPulse className="text-red-500" />,
  DAZED: <ZapOff className="text-yellow-500" />,
  FRIGHTENED: <AlertTriangle className="text-purple-500" />,
  GRAPPLED: <GripHorizontal className="text-green-500" />,
  ONGOING_DAMAGE: <Skull className="text-lime-500" />,
  PRONE: <ArrowDownCircle className="text-orange-500" />,
  RESTRAINED: <Lock className="text-teal-500" />,
  SLOWED: <Timer className="text-blue-500" />,
  SURPRISED: <EyeOff className="text-indigo-500" />,
  TAUNTED: <MessageCircle className="text-pink-500" />,
  UNBALANCED: <Sliders className="text-gray-500" />,
  UNCONSCIOUS: <Moon className="text-slate-500" />,
  WEAKENED: <Thermometer className="text-amber-500" />,
};

export default effectIconMap;
