// Tailwind recipes for the desktop shell. Interactive controls come from shadcn/ui.
const styles: Record<string, string> = {
  'app-shell': 'grid h-screen w-screen min-h-[580px] overflow-hidden grid-cols-[220px_minmax(0,1fr)] max-[1100px]:grid-cols-[185px_minmax(0,1fr)] max-[760px]:block max-[760px]:h-auto max-[760px]:overflow-auto [&>main]:min-w-0',
  sidebar: 'flex min-w-0 flex-col overflow-auto border-r border-border bg-sidebar px-4 pb-4 pt-6 max-[760px]:min-h-0',
  brand: 'px-2 text-2xl font-bold tracking-tight',
  'sidebar-caption': 'mb-10 px-2 text-xs text-muted-foreground max-[760px]:hidden',
  'sidebar-heading': 'mb-3 flex items-center justify-between px-2 [&_h2]:m-0 [&_h2]:text-[11px] [&_h2]:font-semibold [&_h2]:uppercase [&_h2]:tracking-[.14em]',
  'sidebar-list': 'grid content-start gap-1 [&_button]:h-auto [&_button]:min-w-0 [&_button]:justify-start [&_button]:whitespace-normal [&_button]:text-left',
  selected: 'border-sky-600/60 bg-sky-950/70 text-white hover:bg-sky-900/70',
  'sidebar-form': 'mt-3 grid gap-2 border-t border-border px-2 py-3 text-sm [&_label]:grid [&_label]:gap-1',
  'sidebar-bottom': 'mt-auto flex items-center gap-2 px-2 pt-5 text-xs text-muted-foreground max-[760px]:hidden',
  'status-dot': 'size-2 shrink-0 rounded-full bg-emerald-400',
  topbar: 'flex min-h-[115px] items-center justify-between gap-5 border-b border-border bg-card px-7 py-5 max-[760px]:block [&_h1]:mb-1 [&_h1]:text-3xl [&_h1]:font-semibold [&_h1]:tracking-tight',
  'topbar-actions': 'flex flex-wrap items-center gap-3 max-[760px]:mt-3 [&_label]:whitespace-nowrap [&_label]:text-sm [&_input]:ml-1 [&_input]:inline-block [&_input]:w-16',
  'session-pill': 'rounded-full',
  live: 'border-emerald-600/60 bg-emerald-950/50 text-emerald-300',
  columns: 'grid h-[calc(100vh-115px)] min-h-0 grid-cols-[minmax(260px,300px)_minmax(0,1fr)] max-[1100px]:grid-cols-[260px_minmax(0,1fr)] max-[760px]:block max-[760px]:h-auto',
  library: 'min-h-0 overflow-auto border-r border-border bg-muted/20 max-[760px]:overflow-visible',
  'library-tabs': 'grid grid-cols-2 gap-1 border-b border-border p-3 [&_button]:w-full',
  active: 'bg-accent text-accent-foreground',
  'library-panel': 'space-y-3 px-4 py-5',
  'panel-heading': 'mb-4 flex items-center justify-between gap-2 [&_h2]:m-0 [&_h2]:text-xl',
  eyebrow: 'mb-1 text-[11px] font-bold uppercase tracking-[.14em] text-sky-400',
  'empty-hint': 'px-1 py-3 text-sm leading-relaxed text-muted-foreground',
  'list-item': 'my-1.5 flex h-auto w-full flex-col items-start whitespace-normal rounded-lg border border-border bg-card px-3 py-3 text-left [&_small]:mt-1 [&_small]:text-xs [&_small]:text-muted-foreground',
  'member-row': 'flex items-center justify-between gap-2 border-b border-border py-2.5 text-sm [&_small]:block [&_small]:text-xs [&_small]:text-muted-foreground',
  'history-row': 'block border-b border-border py-2.5 text-sm [&_small]:block [&_small]:mt-1 [&_small]:text-xs [&_small]:text-muted-foreground',
  'text-button': 'justify-start border-0 bg-transparent px-0 text-sky-400 hover:bg-transparent hover:text-sky-300',
  'creature-list': 'mb-5',
  'creature-form': 'grid gap-3 rounded-xl border border-border bg-card p-4 [&_h3]:m-0 [&_label]:grid [&_label]:gap-1 [&_label]:text-sm',
  workspace: 'min-h-0 overflow-auto px-8 pb-16 pt-7 max-[1100px]:p-5 max-[760px]:overflow-visible',
  welcome: 'mx-auto mt-[16vh] max-w-lg space-y-4 text-muted-foreground [&_h1]:text-3xl [&_h1]:text-foreground [&_h2]:text-2xl [&_h2]:text-foreground',
  editor: 'mx-auto max-w-[980px] space-y-4',
  'section-header': 'flex items-start justify-between gap-5 max-[1100px]:block [&_h2]:m-0 [&_h2]:text-2xl [&_h2]:font-semibold',
  'editor-actions': 'flex flex-wrap items-center justify-end gap-2 max-[1100px]:mt-3 max-[1100px]:justify-start',
  'draft-status': 'mt-1 text-xs text-amber-300',
  subtle: 'border-transparent bg-transparent text-muted-foreground hover:bg-muted',
  'form-grid': 'grid gap-3 [&_label]:grid [&_label]:gap-1 [&_label]:text-sm',
  card: 'mb-4 block space-y-3 rounded-xl border border-border bg-card p-4 text-card-foreground [&_h3]:mb-2 [&_h3]:text-base [&_h3]:font-semibold',
  'card-heading': 'flex items-start justify-between gap-4',
  muted: 'text-sm leading-relaxed text-muted-foreground',
  row: 'my-2 flex flex-wrap items-center gap-2 [&_span:first-child]:mr-auto [&_input[type=number]]:w-20 [&_input:not([type=number])]:flex-1',
  'roster-row': 'border-t border-border py-2',
  'roster-actions': 'mt-3 flex flex-wrap gap-2 [&_[data-slot=native-select-wrapper]]:min-w-44 [&_[data-slot=native-select-wrapper]]:flex-1',
  check: 'flex items-center gap-2 text-sm',
  primary: 'border-transparent bg-sky-600 text-white hover:bg-sky-500',
  difficulty: 'mb-4 flex items-center justify-between gap-3 rounded-lg border-l-4 border-sky-500 bg-sky-950/40 px-4 py-3 text-sm [&_span]:text-right [&_span]:text-muted-foreground',
  chips: 'mb-3 flex flex-wrap gap-2',
  'combat-bar': 'sticky top-0 z-10 mb-4 flex flex-wrap items-center gap-2 rounded-lg border border-border bg-card/95 p-3 shadow-lg backdrop-blur',
  participant: 'border-t border-border py-3',
  effects: '[&_input]:max-w-40',
  'small-input': 'w-20! flex-none!',
  'add-participant': 'my-3 space-y-3 rounded-lg border border-dashed border-border p-3',
  'session-panel': 'space-y-4',
  'live-label': 'text-xs font-bold uppercase tracking-wide text-emerald-400',
  'victory-row': 'flex items-center gap-2 [&_span]:mr-auto',
  'history-list': 'mt-5',
};

export function u(names: string): string {
  return names.split(/\s+/).map(name => styles[name] ?? '').join(' ');
}
